# Generated by Django 6.0.7 on 2026-08-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('t1', models.CharField(blank=True, max_length=100, null=True)),
                ('t2', models.CharField(blank=True, max_length=100, null=True)),
                ('t3', models.CharField(blank=True, max_length=100, null=True)),
                ('t4', models.CharField(blank=True, max_length=100, null=True)),
                ('t5', models.CharField(blank=True, max_length=100, null=True)),
                ('t6', models.CharField(blank=True, max_length=100, null=True)),
                ('t7', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
            },
        ),
    ]
