# Generated by Django 6.0.7 on 2026-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField()),
                ('image1', models.ImageField(upload_to='photos/package_details/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos/package_details/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos/package_details/')),
                ('about', models.TextField(max_length=500)),
                ('cover', models.TextField(max_length=500)),
                ('photographer', models.TextField(max_length=500)),
                ('videographer', models.TextField(max_length=500)),
                ('drone', models.TextField(max_length=500)),
                ('Deliverables', models.TextField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
