# Generated by Django 6.0.7 on 2026-09-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_booking_booking_id_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/screenshots/'),
        ),
    ]
