# Generated by Django 6.0.7 on 2026-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_booking_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
