# Generated by Django 6.0.7 on 2026-08-30 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit phone number.', regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('event', models.CharField(choices=[('Wedding', 'Wedding'), ('Engagement', 'Engagement'), ('Birthday', 'Birthday'), ('Maternity', 'Maternity'), ('Baby Shoot', 'Baby Shoot'), ('Janue', 'Janue'), ('Corporate Event', 'Corporate Event'), ('Product Photography', 'Product Photography')], default='Wedding', max_length=30)),
                ('event_date', models.DateField()),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
