# Generated by Django 6.0.7 on 2026-08-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'services', 'verbose_name_plural': 'services'},
        ),
        migrations.RenameField(
            model_name='services',
            old_name='price',
            new_name='price1',
        ),
        migrations.AddField(
            model_name='services',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
