# Generated by Django 6.0.7 on 2026-08-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_options_rename_price_services_price1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='view_details',
        ),
    ]
