# Generated by Django 6.0.7 on 2026-08-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_services_view_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('image1', models.ImageField(upload_to='photos/services_details/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos/services_details/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos/services_details/')),
                ('about', models.TextField(max_length=150)),
                ('cover', models.TextField(max_length=200)),
                ('photographer', models.TextField(max_length=200)),
                ('videographer', models.TextField(max_length=200)),
                ('drone', models.TextField(max_length=100)),
                ('Deliverables', models.TextField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
