# Generated by Django 6.0.7 on 2026-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_services_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_details',
            name='Deliverables',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='services_details',
            name='about',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='services_details',
            name='cover',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='services_details',
            name='drone',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='services_details',
            name='photographer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='services_details',
            name='videographer',
            field=models.TextField(max_length=500),
        ),
    ]
