# Generated by Django 6.0.7 on 2026-09-21 07:34

from django.db import migrations, models


def clear_legacy_default_profile_picture(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    Account.objects.filter(profile_picture="profile_pictures/default.png").update(
        profile_picture=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.RunPython(clear_legacy_default_profile_picture, migrations.RunPython.noop),
    ]
