# Generated by Django 6.0.7 on 2026-09-04 15:15

import album.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=album.models.default_expiry)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='shared_albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='albums/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='album.album')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
