# Generated by Django 6.0.7 on 2026-08-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image1', models.ImageField(upload_to='photos/portfolio')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photos/portfolio')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photos/portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolio',
            },
        ),
    ]
